title: Ram Larg
email: pharadonlarg@gmail.com
baseurl: ""
url: "" 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
excerpt_separator: <!--more-->
permalink: /posts/:year/:month/:day/:title